---
name: Packer build AMI 

on:
  # Trigger the workflow on push request,
  # but only for the main branch
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository to build ami
      uses: actions/checkout@v2

    - name: Build AMI
      uses: docker://hashicorp/packer:light
      env:
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws-subnet-id: ${{ secrets.AWS_SUBNET_ID }}
        aws-ami-users: ${{ secrets.AWS_AMI_USERS }}
        aws-source-ami: ${{ secrets.AWS_SOURCE_AMI }}
        PACKER_LOG: 1
      with:
        args: "build -var-file=vars.json ami.json"
      
    - name: Get AMI ID
      run: echo "Successfully Create AMI"

