version: 0.0

os: linux

files:
  - source: target/web-app-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/
  - source: cloudwatch_config.json
    destination: /home/ubuntu/
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file

hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 180
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop-process.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start-process.sh
      timeout: 180
      runas: ubuntu